services:
  app:
    build:
      context: .
    volumes:
      - .:/var/www
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
      - meilisearch
    working_dir: /var/www
    command: php artisan serve --host=0.0.0.0 --port=8000

  db:
    image: mysql:8
    restart: always
    environment:
         MYSQL_DATABASE: ${DB_DATABASE}
         MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  meilisearch:
    image: getmeili/meilisearch:v1.14
    environment:
      MEILI_MASTER_KEY: ${MEILISEARCH_KEY}
    ports:
      - "7700:7700"
    volumes:
      - meili_data:/meili_data

volumes:
  mysql_data:
  meili_data: