services:
  app:
    build:
      context: .
    volumes:
      - .:/var/www
    env_file:
      - .env
    depends_on:
      - db
      - meilisearch
    command: php-fpm

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - .:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  db:
    image: mysql:8
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  meilisearch:
    image: getmeili/meilisearch:v1.14
    environment:
      MEILI_MASTER_KEY: ${MEILISEARCH_KEY}
    ports:
      - "7700:7700"
    volumes:
      - meili_data:/meili_data

volumes:
  mysql_data:
  meili_data:
